### ISSUE TITLE
csrf_token helper method in Laravel 5.4 has been updated

### ISSUE THREAD

**Issue by bryandease** [antonioribeiro/support#10]
`if ( ! function_exists( 'csrf_token' ))
{
	function csrf_token()
	{
		return app()->make('session.store')->getToken();
	}
}`

should now be:

`if ( ! function_exists( 'csrf_token' ))
{
	function csrf_token()
	{
		return app()->make('session')->token();
	}
}`

**Comment by antonioribeiro** [comment]
Should be fixed now. There is no need to create a csrf_token on any Laravel 5, this was a Laravel 4 thing.
