### ISSUE TITLE
Helpers Function env conflicting with laravels env

### ISSUE THREAD

**Issue by tiran133** [antonioribeiro/support#7]
After updating to Laravel 5.2 my APP_ENV environment var was always empty. I figured the cause was your helpers env function. I did not investigate it any further. I just removed the tracker package and with it the support package as well. Since I didn't use it anymore. I just wanted to let you know something is wrong there.

Alex

**Comment by antonioribeiro** [comment]
Thank you, Alex, it was removed from suppor today on master.
