### ISSUE TITLE
Not respecting APP_ENV in user's .env file?

### ISSUE THREAD

**Issue by JesseLeite** [antonioribeiro/support#8]
Curious why this package isn't respecting the user's APP_ENV setting in their .env file?

We have our environment set to `APP_ENV=local`, yet we noticed this when running our seeders:
<img width="492" alt="screen shot 2016-04-05 at 2 11 56 pm" src="https://cloud.githubusercontent.com/assets/5187394/14292967/64721ba2-fb38-11e5-89a9-1828c86d4958.png">

I investigated further, and it seems the setting is being overwritten by your package:
<img width="434" alt="screen shot 2016-04-05 at 2 13 22 pm" src="https://cloud.githubusercontent.com/assets/5187394/14293009/96cf2c66-fb38-11e5-9087-56d1cbacb0c1.png">

If I disable your `putenv()` call [here](https://github.com/antonioribeiro/support/blob/master/src/Environment.php#L172), then my `APP_ENV` setting is respected.  The issue I see is that other packages and/or users may rely on that `APP_ENV` setting.  Is there reason why it needs to be overridden by pragmarx/support?

**Comment by jmfleming** [comment]
This appears to have been resolved with the latest commit.  Would it be possible to go ahead and tag this up a version?

**Comment by JesseLeite** [comment]
@antonioribeiro ping?

**Comment by JesseLeite** [comment]
@antonioribeiro, I pulled in `dev-master` and can verify that it fixes the `APP_ENV` override. Can you tag release and update composer.json for your pragmarx/firewall package please?

**Comment by antonioribeiro** [comment]
Doing it now.

**Comment by antonioribeiro** [comment]
Done. 

Tagged
`support 0.6.6`
`firewall 1.0.1`

**Comment by JesseLeite** [comment]
Thank you!
